### ISSUE TITLE
Not receiving Nest Camera notifications or thumbnail live stream

### ISSUE THREAD

**Issue by nsmithh** [Brandawg93/homebridge-nest-cam#305] opened 2020-10-16 15:54 UTC
Hi! I haven't been able to fenagle my settings to get notifications when my doorbell rings or when my camera notices a person/package. I've looked at some other threads and it doesn't seem like you need an Aware subscription... Also, the camera thumbnails in the homekit app never provide livestreams- they're always thumbnails from hours ago. Honestly, this could all be user error, but I've searched everywhere for a solution. I noticed that my Nest Hello is not saved as a doorbell in the HomeKit app, but just as a camera. Not sure if that's part of the issue. 

I just updated everything last night and there really isn't s debug log output because technically nothing is failing... but I know it's supposed to work- just can't tell what's wrong. 

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: raspberry pi 4
On what iOS version are you having issues: 14.0.1
What camera types are having issues: Nest Hello and Nest Cam Outdoor
Does this issue occur consistently or randomly: Consistently
If applicable, what was the last version that worked properly: never...
```

**Comment by Brandawg93** [comment] 2020-10-16 15:56
I would try clearing your HomeKit cache. It's under Homebridge Settings in the UI.

**Comment by nsmithh** [comment] 2020-10-16 16:17
I’ve done that a couple times and it hasn’t helped

**Comment by Brandawg93** [comment] 2020-10-16 17:10
Can you run homebridge in debug mode and attempt to stream and post the output here?

**Comment by nsmithh** [comment] 2020-10-16 17:51
So when I open the stream it connects and then immediately disconnects making it unable to view the stream in the thumbnail from the homekit homescreen. I'm not sure if this is also the reason I'm unable to receive notifications maybe? 

[10/16/2020, 18:46:43] [Nest-cam] [NexusStreamer] Connected
[10/16/2020, 18:46:44] [Nest-cam] [NexusStreamer] Redirecting...
[10/16/2020, 18:46:44] [Nest-cam] [NexusStreamer] Disconnected
[10/16/2020, 18:46:44] [Nest-cam] [NexusStreamer] Connected
[10/16/2020, 18:46:50] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment] 2020-10-16 17:54
You could be having similar issues as others. The above isn't debug output code. Run `homebridge -D` or turn on DEBUG mode in the settings and copy that output here.

**Comment by nsmithh** [comment] 2020-10-16 18:40
Turned on DEBUG mode this is what I got- hopefully this is it?

[10/16/2020, 19:34:34] [Nest-cam] waiting for socket to connect
[10/16/2020, 19:34:34] [Nest-cam] VIDEO: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[10/16/2020, 19:34:34] [Nest-cam] AUDIO: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[10/16/2020, 19:34:34] [Nest-cam] RETURN AUDIO: [udp @ 0x2d79990] attempted to set receive buffer to size 393216 but it only ended up set as 360448
[udp @ 0x2d79af0] attempted to set receive buffer to size 393216 but it only ended up set as 360448

[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] Connected
[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] OK
[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] Redirect
[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] Redirecting...
[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] Disconnected
[10/16/2020, 19:34:34] [Nest-cam] Using HIGH quality stream.
[10/16/2020, 19:34:34] [Nest-cam] waiting for socket to connect
[10/16/2020, 19:34:34] [Nest-cam] [NexusStreamer] Connected
[10/16/2020, 19:34:34] [Nest-cam] Checking for alerts on Front Door
[10/16/2020, 19:34:35] [Nest-cam] [NexusStreamer] OK
[10/16/2020, 19:34:35] [Nest-cam] [NexusStreamer] Playback Begin
[10/16/2020, 19:34:36] [Nest-cam] AUDIO: Input #0, aac, from 'pipe:':
  Duration: N/A, bitrate: 66 kb/s
    Stream #0:0: Audio: aac, 48000 Hz, mono, s16, 66 kb/s

[10/16/2020, 19:34:36] [Nest-cam] AUDIO: Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> aac (libfdk_aac))

[10/16/2020, 19:34:36] [Nest-cam] AUDIO: Output #0, rtp, to 'srtp://192.168.1.213:53022?rtcpport=53022&localrtcpport=38287&pkt_size=188':
  Metadata:
    encoder         : Lavf58.45.100

[10/16/2020, 19:34:36] [Nest-cam] AUDIO:     Stream #0:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, 24 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libfdk_aac

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: Input #0, h264, from 'pipe:':
  Duration: N/A, start: 1602873275.454397, bitrate: N/A

[10/16/2020, 19:34:36] [Nest-cam] VIDEO:     Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 1152x864 [SAR 1:1 DAR 4:3], 15 fps, 15 tbr, 1200k tbn, 30 tbc

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> h264 (libx264))

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: [swscaler @ 0x27fd890] deprecated pixel format used, make sure you did set range correctly

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: [libx264 @ 0x2587ae0] using SAR=1/1

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: [libx264 @ 0x2587ae0] using cpu capabilities: ARMv6 NEON

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: [libx264 @ 0x2587ae0] profile Constrained Baseline, level 3.2, 4:2:0, 8-bit

[10/16/2020, 19:34:36] [Nest-cam] VIDEO: Output #0, rtp, to 'srtp://192.168.1.213:62442?rtcpport=62442&localrtcpport=32997&pkt_size=1378':
  Metadata:
    encoder         : Lavf58.45.100
    Stream #0:0: Video: h264 (libx264), yuv420p, 1152x864 [SAR 1:1 DAR 4:3], q=-1--1, 30 fps, 90k tbn, 30 tbc
    Metadata:
      encoder         : Lavc58.91.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A

[10/16/2020, 19:34:36] [Nest-cam] AUDIO: size=       6kB time=00:00:01.55 bitrate=  29.2kbits/s speed= 2.9x    
[10/16/2020, 19:34:37] [Nest-cam] VIDEO: frame=   14 fps=0.0 q=14.0 size=     309kB time=00:00:00.43 bitrate=5849.6kbits/s dup=1 drop=0 speed=0.806x    
[10/16/2020, 19:34:37] [Nest-cam] AUDIO: size=       8kB time=00:00:02.15 bitrate=  28.9kbits/s speed=1.84x    
[10/16/2020, 19:34:37] [Nest-cam] VIDEO: frame=   31 fps= 29 q=15.0 size=     370kB time=00:00:01.00 bitrate=3032.9kbits/s dup=1 drop=0 speed=0.943x    
[10/16/2020, 19:34:38] [Nest-cam] AUDIO: size=      10kB time=00:00:02.76 bitrate=  28.6kbits/s speed=1.62x    
[10/16/2020, 19:34:38] [Nest-cam] VIDEO: frame=   43 fps= 27 q=14.0 size=     406kB time=00:00:01.40 bitrate=2373.5kbits/s dup=1 drop=0 speed=0.893x    
[10/16/2020, 19:34:38] [Nest-cam] AUDIO: size=      11kB time=00:00:03.18 bitrate=  28.5kbits/s speed=1.42x    
[10/16/2020, 19:34:38] [Nest-cam] VIDEO: frame=   50 fps= 24 q=14.0 size=     427kB time=00:00:01.63 bitrate=2142.2kbits/s dup=1 drop=0 speed=0.784x    
[10/16/2020, 19:34:39] [Nest-cam] AUDIO: size=      13kB time=00:00:03.79 bitrate=  28.5kbits/s speed=1.38x    
[10/16/2020, 19:34:39] [Nest-cam] VIDEO: frame=   59 fps= 23 q=14.0 size=     450kB time=00:00:01.93 bitrate=1908.6kbits/s dup=1 drop=0 speed=0.742x    
[10/16/2020, 19:34:39] [Nest-cam] AUDIO: size=      15kB time=00:00:04.23 bitrate=  28.5kbits/s speed= 1.3x    
[10/16/2020, 19:34:39] [Nest-cam] Checking for alerts on Front Door
[10/16/2020, 19:34:39] [Nest-cam] VIDEO: frame=   66 fps= 21 q=17.0 size=     570kB time=00:00:02.16 bitrate=2155.3kbits/s dup=1 drop=0 speed=0.688x    
[10/16/2020, 19:34:40] [Nest-cam] AUDIO: size=      17kB time=00:00:04.81 bitrate=  28.4kbits/s speed=1.27x    
[10/16/2020, 19:34:40] [Nest-cam] VIDEO: frame=   72 fps= 19 q=15.0 size=     641kB time=00:00:02.36 bitrate=2219.7kbits/s dup=1 drop=0 speed=0.636x    
[10/16/2020, 19:34:40] [Nest-cam] AUDIO: size=      18kB time=00:00:05.32 bitrate=  28.3kbits/s speed=1.23x    
[10/16/2020, 19:34:40] [Nest-cam] (Not implemented) Received request to reconfigure to: {"width":640,"height":360,"fps":30,"max_bit_rate":132,"rtcp_interval":0.5}
[10/16/2020, 19:34:41] [Nest-cam] VIDEO: frame=   83 fps= 20 q=14.0 size=     674kB time=00:00:02.73 bitrate=2020.1kbits/s dup=1 drop=0 speed=0.646x    
[10/16/2020, 19:34:41] [Nest-cam] AUDIO: size=      20kB time=00:00:05.87 bitrate=  28.3kbits/s speed=1.21x    
[10/16/2020, 19:34:41] [Nest-cam] VIDEO: frame=   91 fps= 19 q=14.0 size=     697kB time=00:00:03.00 bitrate=1902.9kbits/s dup=1 drop=0 speed=0.631x    
[10/16/2020, 19:34:41] [Nest-cam] AUDIO: size=      22kB time=00:00:06.41 bitrate=  28.3kbits/s speed= 1.2x    
[10/16/2020, 19:34:42] [Nest-cam] VIDEO: frame=   99 fps= 19 q=16.0 size=     727kB time=00:00:03.26 bitrate=1824.0kbits/s dup=1 drop=0 speed=0.62x    
[10/16/2020, 19:34:42] [Nest-cam] AUDIO: size=      24kB time=00:00:06.89 bitrate=  28.3kbits/s speed=1.18x    
[10/16/2020, 19:34:42] [Nest-cam] VIDEO: frame=  106 fps= 18 q=14.0 size=     752kB time=00:00:03.50 bitrate=1760.2kbits/s dup=1 drop=0 speed=0.603x    
[10/16/2020, 19:34:42] [Nest-cam] AUDIO: size=      26kB time=00:00:07.43 bitrate=  28.3kbits/s speed=1.17x    
[10/16/2020, 19:34:43] [Nest-cam] VIDEO: frame=  115 fps= 18 q=15.0 size=     781kB time=00:00:03.80 bitrate=1684.0kbits/s dup=1 drop=0 speed=0.596x    
[10/16/2020, 19:34:43] [Nest-cam] AUDIO: size=      27kB time=00:00:07.91 bitrate=  28.2kbits/s speed=1.15x    
[10/16/2020, 19:34:43] [Nest-cam] VIDEO: frame=  124 fps= 18 q=21.0 size=     866kB time=00:00:04.10 bitrate=1729.6kbits/s dup=1 drop=0 speed=0.59x    
[10/16/2020, 19:34:43] [Nest-cam] AUDIO: size=      29kB time=00:00:08.46 bitrate=  28.2kbits/s speed=1.14x    
[10/16/2020, 19:34:44] [Nest-cam] VIDEO: frame=  132 fps= 18 q=14.0 size=     997kB time=00:00:04.36 bitrate=1869.6kbits/s dup=1 drop=0 speed=0.585x    
[10/16/2020, 19:34:44] [Nest-cam] AUDIO: size=      31kB time=00:00:08.97 bitrate=  28.2kbits/s speed=1.12x    
[10/16/2020, 19:34:44] [Nest-cam] VIDEO: frame=  139 fps= 17 q=14.0 size=    1018kB time=00:00:04.60 bitrate=1813.2kbits/s dup=1 drop=0 speed=0.577x    
[10/16/2020, 19:34:44] [Nest-cam] Checking for alerts on Front Door
[10/16/2020, 19:34:44] [Nest-cam] AUDIO: size=      33kB time=00:00:09.55 bitrate=  28.2kbits/s speed=1.12x    
[10/16/2020, 19:34:45] [Nest-cam] Stopped streaming session!
[10/16/2020, 19:34:45] [Nest-cam] RETURN AUDIO: Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, sdp, from 'pipe:0':
  Metadata:
    title           : Talk
  Duration: N/A, bitrate: N/A
    Stream #0:0: Audio: aac, 16000 Hz, mono, s16
Stream mapping:
  Stream #0:0 -> #0:0 (aac (libfdk_aac) -> speex (libspeex))
Finishing stream 0:0 without any data written to it.

[10/16/2020, 19:34:45] [Nest-cam] RETURN AUDIO: Output #0, data, to 'pipe:1':
  Metadata:
    title           : Talk
    encoder         : Lavf58.45.100

[10/16/2020, 19:34:45] [Nest-cam] RETURN AUDIO:     Stream #0:0: Audio: speex (libspeex), 16000 Hz, mono, s16, 27 kb/s
    Metadata:
      encoder         : Lavc58.91.100 libspeex

[10/16/2020, 19:34:45] [Nest-cam] RETURN AUDIO: size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown

[10/16/2020, 19:34:45] [Nest-cam] RETURN AUDIO: Exiting normally, received signal 15.

[10/16/2020, 19:34:45] [Nest-cam] VIDEO: frame=  147 fps= 17 q=14.0 size=    1043kB time=00:00:04.86 bitrate=1756.3kbits/s dup=1 drop=0 speed=0.572x    
[10/16/2020, 19:34:45] [Nest-cam] VIDEO: frame=  147 fps= 17 q=14.0 Lsize=    1043kB time=00:00:04.86 bitrate=1756.3kbits/s dup=1 drop=0 speed=0.567x    
video:1032kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.148674%

[10/16/2020, 19:34:45] [Nest-cam] VIDEO: [libx264 @ 0x2587ae0] frame I:1     Avg QP:20.00  size:132753
[libx264 @ 0x2587ae0] frame P:146   Avg QP:15.15  size:  6325
[libx264 @ 0x2587ae0] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x2587ae0] mb P  I16..4:  0.1%  0.0%  0.0%  P16..4: 16.2%  0.0%  0.0%  0.0%  0.0%    skip:83.6%

[10/16/2020, 19:34:45] [Nest-cam] VIDEO: [libx264 @ 0x2587ae0] coded y,uvDC,uvAC intra: 80.4% 58.0% 10.5% inter: 8.1% 4.2% 0.2%
[libx264 @ 0x2587ae0] i16 v,h,dc,p: 26% 26% 31% 17%
[libx264 @ 0x2587ae0] i8c dc,h,v,p: 48% 23% 19% 10%
[libx264 @ 0x2587ae0] kb/s:1724.51

[10/16/2020, 19:34:45] [Nest-cam] VIDEO: Exiting normally, received signal 15.

[10/16/2020, 19:34:45] [Nest-cam] Stopped streaming session!
[10/16/2020, 19:34:45] [Nest-cam] [NexusStreamer] Playback End
[10/16/2020, 19:34:45] [Nest-cam] [NexusStreamer] Disconnected

**Comment by Brandawg93** [comment] 2020-10-18 16:28
This seems to be a known homebridge issue and a duplicate of #279. If I find out more from the homebridge team, I will let you know here.

**Comment by Brandawg93** [comment] 2020-12-05 17:06
Homebridge v1.2.4 was just released. If the release fixes this issue, please let me know here.

**Comment by Brandawg93** [comment] 2020-12-08 20:45
Since this is a duplicate of #279, I'm going to close this issue. If you want to receive further updates on this, you can subscribe to that issue.

**Closed by Brandawg93** 2020-12-08 20:45 UTC
Labels: bug, duplicate, help wanted
