### ISSUE TITLE
Nest Hello Doorbell support

### ISSUE THREAD

**Issue by novemTeam** [Brandawg93/homebridge-nest-cam#17] opened 2020-02-25 19:18 UTC
Are there plans to add doorbell support? Motion sensors are not enough. I would love a ring sensor/ and notifications.

**Comment by Brandawg93** [comment] 2020-02-25 19:20
It's my understanding that this functionality is built into [homebridge-nest](https://github.com/chrisjshull/homebridge-nest).

**Comment by novemTeam** [comment] 2020-02-25 19:40
No, it doesn't support the Nest Hello.
This is the list:

### HomeKit Accessory Types

**Home**

- Switch accessory (Home Occupied) indicating detected Home/Away state - can be manually changed
**Nest Thermostat (+ Temperature Sensors)**

- Thermostat accessory with ambient temperature and humidity sensors, mode control (heat/cool/auto/off), and target temperature control
- Switch accessory (Eco Mode) for turning on and off Eco Mode
- Fan accessory for controlling the fan (except the EU/UK model of the Nest Thermostat E, which does not have a fan control)
- TemperatureSensor accessory indicating the ambient temperature at the thermostat (disabled by default if no Temperature Sensors are present - temperature is reported by the base Thermostat accessory)
- TemperatureSensor accessory indicating the ambient temperature where each additional Nest - Temperature Sensor is located
- HumiditySensor accessory indicating the relative humidity at the thermostat (disabled by default - humidity is reported by the base Thermostat accessory)
**Nest Protect**

- SmokeSensor accessory (Smoke) indicating smoke detected
- CarbonMonoxideSensor accessory (Carbon Monoxide) indicating CO detected
- MotionSensor accessory (Motion) indicating motion detected near the Protect device (AC wired Protects only)
**Nest x Yale Lock**

- LockMechanism accessory

**Comment by Brandawg93** [comment] 2020-02-25 19:56
Interestingly, digging through the commits, it looks like homebridge-nest had support for the doorbell then dropped it and camera motion support. I don't think it would be difficult adding [support for the doorbell](https://github.com/Samfox2/homebridge-videodoorbell), the only problem is I don't own one. If I ever get one in the future, I'll attempt to add support.

**Comment by novemTeam** [comment] 2020-02-25 20:15
Oh damn it, what a bummer. Hopelfully soon ;)

Would have thought more people would want the Nest Hello in Homekit. Would give me so much possibilities. 

But thanks in advance.

**Comment by novemTeam** [comment] 2020-02-25 20:20
Reading this:

https://github.com/chrisjshull/homebridge-nest/pull/61

Apparently it’s not possible? But i thought the Starlink Home Hub was able to add the doorbell to Homekit? So looks like it would be possible?

**Comment by Brandawg93** [comment] 2020-02-25 20:30
If you receive a notification via the app then I'd assume there to be a way. I would assume the open-source homebridge-nest plugin has minimal functionality compared to the dev's paid alternative, Starling Home Hub. If I either receive enough donations or get access to one somehow via the [Discord Testing Server](https://discord.gg/E6dnwsE), I'll make an honest attempt at adding those features.

**Comment by danch99** [comment] 2020-05-10 19:38
Hi,

I’ve installed Hoobs and Nest-cam2 to get the Hello doorbell motion notifications in HomeKit and SmartThings (with the help of some other tricks), and then I found this thread ! 
Any chance you’re gonna add the motion notifications soon ? please 😄

**Comment by Brandawg93** [comment] 2020-05-10 19:41
Unfortunately, I still do not have a Hello doorbell to test with.

**Comment by danch99** [comment] 2020-05-10 19:48
Wouah, you’ve answered 3 minutes later ! Thanks a lot.

Hope you’ll get one soon and can help us.
Thanks a lot.

**Comment by danch99** [comment] 2020-05-12 00:24
Hi Brandon,
I discovered today that notifications works finally ! But not all of them though.
Motion events, even if they are in the defined areas doesn’t go to HomeKit. But “Person notifications” are sent to HomeKit ! Which is pretty cool.

I was wondering if it’s possible to add a bit more control and to choose to get all motion notifications in the defined areas ?

Thanks

**Comment by Brandawg93** [comment] 2020-05-12 00:33
It may be possible. I’ll look into this now that v2.0 is released.

**Comment by danch99** [comment] 2020-05-12 00:39
Cool
v2.0 is not compatible with Hoobs ??!! Ouch. 
What am I gonna miss ?
Why ?

**Comment by Brandawg93** [comment] 2020-05-12 00:44
I actually didn’t find out until after updating the plugin. HOOBS runs an older version of homebridge and support is almost gone. I’d suggest converting to homebridge, but if you want to continue with HOOBS, you can install an older version of this plugin via `npm -g install homebridge-nest-cam2@hoobs`.

**Comment by danch99** [comment] 2020-05-12 00:50
I tried Hoobs because I like the web UI and It’s pretty simple to use and to install plugins. But if I get other troubles because it runs an old version of homebridge, I might reconsider my choice. 🤔

**Comment by Brandawg93** [comment] 2020-05-12 00:56
I’ve spoken with other plugin developers and they are dropping support for HOOBS as well. I’d expect other plugins to stop working as they get updated.

**Comment by danch99** [comment] 2020-05-12 00:59
Ok you convinced me 😉
And as I’m checking homebridge again, i found a UI plugin with is pretty nice !
I should give it a try.

Thanks Brandon

**Comment by novemTeam** [comment] 2020-05-12 05:18
So there are person notifications, but no doorbell ring notifications? Am I understanding this? Also you are saying support for hoobs will be dropped?
Can i use hassio?

**Comment by Brandawg93** [comment] 2020-05-12 11:02
Doorbell ring notifications have not been implemented yet because I do not have one to use for testing. You can use anything that uses homebridge >= 1.0.0. HOOBS uses an older homebridge.

**Comment by novemTeam** [comment] 2020-05-12 11:18
Is there something I/we can do? I have 2 nest hello doorbells

**Comment by Brandawg93** [comment] 2020-05-12 11:23
No, but thanks for the offer. I just need to get one to mess around with the code, but spending $300 on developing a free plugin is out of my price range at the moment.

**Comment by Brandawg93** [comment] 2020-05-13 00:57
v2.1.0-beta.0 has doorbell notification support. Let me know if it works for someone.

**Comment by novemTeam** [comment] 2020-05-13 04:51
Nice! I need some help with installing this beta. I have 2 raspberry pi, one running hoobs and one running Home Assistant. How can I install it?

**Comment by Brandawg93** [comment] 2020-05-13 05:22
This plugin does not work with HOOBS, but you can install with `npm -g install homebridge-nest-cam2@beta`.

**Comment by novemTeam** [comment] 2020-05-13 15:52
So I just erased HOOBS from my raspberry and installed homebridge. I then installed the beta of Nest Cam2 and tried to ring my doorbell. I made sure notifications are turned on, but I didn't receive a notification.

**Comment by Brandawg93** [comment] 2020-05-13 15:58
Ok. Thanks for heads up. I’ll have to do more testing and I’ll release a new beta and let you know.

**Comment by Brandawg93** [comment] 2020-05-13 16:51
I've confirmed with another user that the doorbell notifications are working. Do you see "doorbell" as an option under notifications?

**Comment by novemTeam** [comment] 2020-05-14 18:48
No, i dont see the option “doorbell”

**Comment by novemTeam** [comment] 2020-05-15 08:23
![7DFE1332-6C04-45EC-A578-71A111E41F86](https://user-images.githubusercontent.com/44820440/82028494-01f02e80-9696-11ea-8382-f8e022059a51.jpeg)

I do have the beta tho.

**Comment by Brandawg93** [comment] 2020-05-15 12:20
I just released a new beta (v2.1.0-beta.4) that I have confirmed works with several other users. Try it out and let me know if you have issues.

**Comment by novemTeam** [comment] 2020-05-15 18:52
Nice! I can confirm that it works. Now i have one more question, is it possible that you make a real button from the doorbell in homekit? So when the door rings, i can let it turn on a light... . 

https://www.npmjs.com/package/homebridge-ring

With this doorbell from Ring, it is works via a button in homekit via homebridge.

**Comment by brn2prgrm** [comment] 2020-05-19 03:22
> Nice! I can confirm that it works. Now i have one more question, is it possible that you make a real button from the doorbell in homekit? So when the door rings, i can let it turn on a light... .
> 
> https://www.npmjs.com/package/homebridge-ring
> 
> With this doorbell from Ring, it is works via a button in homekit via homebridge.

I agree, a button would be more helpful. I feel the Nest app does a better job than Home.app does for doorbell notifications, but if I had a button to create automations, then this would be much more useful!

**Comment by Brandawg93** [comment] 2020-05-19 16:08
v2.2.0 has been released with doorbell automation support. Let me know if it works you!

**Comment by novemTeam** [comment] 2020-05-19 16:20
Yep! It works like a charm! Thanks a lot!
You really pushed this plugin to the next level.

**Closed** 2020-05-19 16:21 UTC
Labels: enhancement
