### ISSUE TITLE
This plugin generated a warning from the characteristic 'Model'

### ISSUE THREAD

**Issue by jtochterman** [Brandawg93/homebridge-nest-cam#405] opened 2021-03-01 23:53 UTC
This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.

Please answer these questions before submitting this issue:
```
On what device are you running homebridge:  Not device specific, it is log entry.
On what iOS version are you having issues: n/a
What camera types are having issues: n/a
Does this issue occur consistently or randomly: consistently
If applicable, what was the last version that worked properly: seems to be working fine, just a warning in the log entry.

**Comment by Brandawg93** [comment] 2021-03-01 23:55
Can you copy and paste more of the logs here? Otherwise I have no idea where the bug could be.

**Comment by gadawg87** [comment] 2021-03-03 18:19
I'm seeing the same. Here's the error with debug on.

`[3/3/2021, 1:14:54 PM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/3/2021, 1:14:54 PM] [homebridge-nest-cam] Error: 
    at Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2082:16)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1484:21)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.handleGetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:648:24)
    at Characteristic.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2229:22)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Characteristic.toHAP (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:1434:24)
    at _loop_1 (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:601:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Service.js:450:21
    at new Promise (<anonymous>)
    at Service.toHAP (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:549:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1034:72
    at Array.map (<anonymous>)`

**Comment by Brandawg93** [comment] 2021-03-03 18:51
This should be fixed in v7.1.2. 
Note: You may need to clear your accessory cache in the Homebridge settings for the changes to take effect. If you still have issues with this, feel free to reopen this.

**Closed by Brandawg93** 2021-03-03 18:51 UTC
Labels: bug

**Comment by jtochterman** [comment] 2021-03-05 15:00
Apologies, I looked to see where to turn on more detailed logging and couldn't find it. I applied the latest update the other day and the warning is still there:

[3/5/2021, 4:45:02 AM] [Homebridge UI] Running scheduled instance backup...
[3/5/2021, 4:45:02 AM] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-ovJRng/homebridge-backup-0EB9B633BF53.tar.gz
[3/5/2021, 5:02:31 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 5:39:40 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 7:37:01 AM] [Ring] Front Door Detected Motion
[3/5/2021, 7:46:40 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 8:15:01 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 8:58:03 AM] [Ring] Front Door Detected Motion
[3/5/2021, 9:00:31 AM] [Ring] Front Door Detected Motion
[3/5/2021, 9:08:41 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 9:10:18 AM] [Ring] Front Door Detected Motion
[3/5/2021, 9:51:27 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 9:53:11 AM] [homebridge-nest-cam] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[3/5/2021, 9:57:25 AM] [Ring] Front Door Detected Motion

**Comment by Brandawg93** [comment] 2021-03-05 15:03
You will need to delete your accessory cache for each camera in Homebridge settings.

The issue was caused by the plugin giving an empty string as the model of camera that you have. For instance, if you have an older dropcam or a Nest Hub Max, that is probably what is throwing the error.

**Comment by jtochterman** [comment] 2021-03-05 21:47
I will do that. I know one of those Nest cams is one of the last DropCams. Thanks!

**Comment by jtochterman** [comment] 2021-03-05 21:56
I went in and cleared just that particular camera from the cache and the warning went away. Thanks!
