### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined at NestCam.checkAlerts 

### ISSUE THREAD

**Issue by byronavory** [Brandawg93/homebridge-nest-cam#63] opened 2020-05-23 12:49 UTC
Error keeps throwing since update to homebridge-nest-cam v2.3.2 every 10 seconds. It appears to be superficial. I am not noticing any issue other than a 1%-2% increase in CPU load.
_"TypeError: Cannot read property 'filter' of undefined at NestCam.checkAlerts (/usr/local/lib/node_modules/homebridge-nest-cam/src/nestcam.ts:108:50) at processTicksAndRejections (internal/process/task_queues.js:97:5)"_

Raspbian GNU/Linux Buster (10)
Node.js Version: v12.16.3
Npm Version: v6.14.4
----------------------------------------------------------------------------------------
_

> [5/23/2020, 8:35:52 AM] [Nest-cam] Configuring accessory Driveway
> --
> [5/23/2020, 8:35:52 AM] [Nest-cam] Configuring accessory Patio
> [5/23/2020, 8:35:52 AM] [Nest-cam] Setting Field Test to false
> [5/23/2020, 8:35:52 AM] [Nest-cam] Authenticating via Google.
> [5/23/2020, 8:35:57 AM] Homebridge is running on port 51434.
> [5/23/2020, 8:36:02 AM] [Nest-cam] Checking for alerts on Driveway
> [5/23/2020, 8:36:02 AM] [Nest-cam] Updating info for Driveway
> [5/23/2020, 8:36:02 AM] [Nest-cam] Checking for alerts on Patio
> [5/23/2020, 8:36:02 AM] [Nest-cam] Updating info for Patio
> [5/23/2020, 8:36:03 AM] [Nest-cam] TypeError: Cannot read property 'filter' of undefined at NestCam.checkAlerts (/usr/local/lib/node_modules/homebridge-nest-cam/src/nestcam.ts:108:50) at processTicksAndRejections (internal/process/task_queues.js:97:5)
> [5/23/2020, 8:36:12 AM] [Nest-cam] Checking for alerts on Driveway
> [5/23/2020, 8:36:12 AM] [Nest-cam] Updating info for Front Yard
> [5/23/2020, 8:36:12 AM] [Nest-cam] Checking for alerts on Patio
> [5/23/2020, 8:36:12 AM] [Nest-cam] Updating info for Patio
> [5/23/2020, 8:36:13 AM] [Nest-cam] TypeError: Cannot read property 'filter' of undefined at NestCam.checkAlerts (/usr/local/lib/node_modules/homebridge-nest-cam/src/nestcam.ts:108:50) at processTicksAndRejections (internal/process/task_queues.js:97:5)

_

**Comment by Brandawg93** [comment] 2020-05-23 13:06
It looks like the issue is [this line of code](https://github.com/Brandawg93/homebridge-nest-cam/blob/master/src/nestcam.ts#L108). Do you have something set for `alertTypes` in your config? This is a feature I’m working on to allow configurable motion alerts. By default, it is an array with one element “motion”. Have you attempted to modify this?

**Comment by byronavory** [comment] 2020-05-23 13:23
Nothing in my homebridge config. I did have"motionDetection" set to false, however, I tried removing all advanced config options in config.json and still am getting the error. 
It may be worth noting that I accidentally upgraded to the Nest Aware Plus subscription. I wonder if this is related to the change in the API from Google.

**Comment by Brandawg93** [comment] 2020-05-23 14:35
I've created a new test version. You can install it via `npm -g i homebridge-nest-cam@test`. Let me know if it fixes your issue.

**Comment by byronavory** [comment] 2020-05-23 17:47
I loaded the test version and let it run for a few hours... The errors stopped. There is still a process checking alerts every 10 seconds. I don't know if that was normal before. You don't notice with debugging off.
-------------------------------------------------------------------------------
[5/23/2020, 10:38:19 AM] [Nest-cam] Checking for alerts on Driveway
[5/23/2020, 10:38:19 AM] [Nest-cam] Updating info for Front Yard
[5/23/2020, 10:38:19 AM] [Nest-cam] Checking for alerts on Patio
[5/23/2020, 10:38:19 AM] [Nest-cam] Updating info for Patio
[5/23/2020, 10:38:29 AM] [Nest-cam] Checking for alerts on Driveway
[5/23/2020, 10:38:29 AM] [Nest-cam] Updating info for Front Yard
[5/23/2020, 10:38:29 AM] [Nest-cam] Checking for alerts on Patio
[5/23/2020, 10:38:29 AM] [Nest-cam] Updating info for Patio

**Comment by Brandawg93** [comment] 2020-05-23 17:50
Yes, it is expected. The plugin checks for alerts and status updates every 10 seconds. I'm working on a few other fixes, and I'll publish a new version with this included. Feel free to run the test version for now if you like.

**Comment by byronavory** [comment] 2020-05-23 17:51
I am going to keep letting it run and see if it throws any other errors... Thanks for being so on top of this!

**Comment by Brandawg93** [comment] 2020-05-24 15:36
This has been fixed in the latest version.

**Closed by Brandawg93** 2020-05-24 15:36 UTC
Labels: bug
