### ISSUE TITLE
Camera is stuck on spinner (not updating?)

### ISSUE THREAD

**Issue by aramikg** [Brandawg93/homebridge-nest-cam#265] opened 2020-09-17 23:42 UTC
**Before Submitting an Issue**

https://github.com/Brandawg93/homebridge-nest-cam/wiki/Troubleshooting

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam`

Also include debug log output from startup through seeing the issue:
`homebridge -D`

**Describe the bug**
The camera show up in my home app on iOS and tvOS... when I tap to view I just see the first frame and the spinner just stays there ... the only error I see in the log is this. 

```
UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/homebridge-nest-cam/node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7021) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7021) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

After a while it says that it stopped response and disconnects.

```
[9/17/2020, 4:44:02 PM] [Nest-cam] VIDEO: frame=  280 fps= 16 q=13.0 size=     683kB time=00:00:09.30 bitrate= 601.9kbits/s dup=1 drop=0 speed=0.533x    
[9/17/2020, 4:44:02 PM] [Nest-cam] VIDEO: frame=  288 fps= 16 q=13.0 size=     686kB time=00:00:09.56 bitrate= 587.5kbits/s dup=1 drop=0 speed=0.532x    
[9/17/2020, 4:44:03 PM] [Nest-cam] VIDEO: frame=  296 fps= 16 q=13.0 size=     689kB time=00:00:09.83 bitrate= 574.3kbits/s dup=1 drop=0 speed=0.531x    
[9/17/2020, 4:44:03 PM] [Nest-cam] VIDEO: frame=  304 fps= 16 q=13.0 size=     693kB time=00:00:10.10 bitrate= 561.8kbits/s dup=1 drop=0 speed=0.53x    
[9/17/2020, 4:44:04 PM] [Nest-cam] VIDEO: frame=  312 fps= 16 q=14.0 size=     739kB time=00:00:10.36 bitrate= 583.9kbits/s dup=1 drop=0 speed=0.529x    
[9/17/2020, 4:44:04 PM] [Nest-cam] VIDEO: frame=  320 fps= 16 q=13.0 size=     759kB time=00:00:10.63 bitrate= 584.4kbits/s dup=1 drop=0 speed=0.527x    
[9/17/2020, 4:44:05 PM] [Nest-cam] Checking for alerts on Front Door
[9/17/2020, 4:44:05 PM] [Nest-cam] Setting Front Door Motion Motion to false
[9/17/2020, 4:44:05 PM] [Nest-cam] VIDEO: frame=  329 fps= 16 q=13.0 size=     763kB time=00:00:10.93 bitrate= 571.4kbits/s dup=1 drop=0 speed=0.528x    
[9/17/2020, 4:44:06 PM] [Nest-cam] VIDEO: frame=  336 fps= 16 q=13.0 size=     765kB time=00:00:11.16 bitrate= 561.4kbits/s dup=1 drop=0 speed=0.526x    
[9/17/2020, 4:44:06 PM] [Nest-cam] VIDEO: frame=  341 fps= 16 q=13.0 size=     767kB time=00:00:11.33 bitrate= 554.7kbits/s dup=1 drop=0 speed=0.521x    
[9/17/2020, 4:44:06 PM] [Nest-cam] VIDEO: frame=  351 fps= 16 q=13.0 size=     771kB time=00:00:11.66 bitrate= 541.7kbits/s dup=1 drop=0 speed=0.524x    
[9/17/2020, 4:44:07 PM] [Nest-cam] Checking for alerts on Backyard
[9/17/2020, 4:44:07 PM] [Nest-cam] Checking for alerts on Front Yard
[9/17/2020, 4:44:07 PM] [Nest-cam] Checking for alerts on Living Room
[9/17/2020, 4:44:07 PM] [Nest-cam] Setting Backyard Motion Motion to false
[9/17/2020, 4:44:07 PM] [Nest-cam] Setting Living Room Motion Motion to false
[9/17/2020, 4:44:07 PM] [Nest-cam] Setting Front Yard Motion Motion to false
[9/17/2020, 4:44:07 PM] [Nest-cam] VIDEO: frame=  353 fps= 15 q=13.0 size=     773kB time=00:00:11.73 bitrate= 539.4kbits/s dup=1 drop=0 speed=0.513x    
[9/17/2020, 4:44:08 PM] [Nest-cam] VIDEO: frame=  369 fps= 16 q=17.0 size=     807kB time=00:00:12.26 bitrate= 538.9kbits/s dup=1 drop=0 speed=0.525x    
[9/17/2020, 4:44:08 PM] [Nest-cam] VIDEO: frame=  377 fps= 16 q=13.0 size=     846kB time=00:00:12.53 bitrate= 552.7kbits/s dup=1 drop=0 speed=0.523x    
[9/17/2020, 4:44:09 PM] [Nest-cam] VIDEO: frame=  385 fps= 16 q=13.0 size=     850kB time=00:00:12.80 bitrate= 544.0kbits/s dup=1 drop=0 speed=0.523x    
[9/17/2020, 4:44:09 PM] [Nest-cam] VIDEO: frame=  393 fps= 16 q=13.0 size=     854kB time=00:00:13.06 bitrate= 535.1kbits/s dup=1 drop=0 speed=0.523x    
[9/17/2020, 4:44:10 PM] [Nest-cam] VIDEO: frame=  401 fps= 16 q=13.0 size=     857kB time=00:00:13.33 bitrate= 526.8kbits/s dup=1 drop=0 speed=0.522x    
[9/17/2020, 4:44:10 PM] [Nest-cam] VIDEO: frame=  409 fps= 16 q=13.0 size=     861kB time=00:00:13.60 bitrate= 518.6kbits/s dup=1 drop=0 speed=0.522x    
[9/17/2020, 4:44:11 PM] [Nest-cam] VIDEO: frame=  413 fps= 15 q=13.0 size=     863kB time=00:00:13.73 bitrate= 514.9kbits/s dup=1 drop=0 speed=0.515x    
[9/17/2020, 4:44:11 PM] [Nest-cam] Stopped streaming session!
[9/17/2020, 4:44:11 PM] [Nest-cam] [NexusStreamer] Playback End
[9/17/2020, 4:44:11 PM] [Nest-cam] [NexusStreamer] Disconnected
```
**To Reproduce**

1. open the home app and view a camera

**Expected behavior**

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge: macOS
On what iOS version are you having issues: ios13.7 / io14
What camera types are having issues: nest cam indoor and outdoor
Does this issue occur consistently or randomly: consistently
If applicable, what was the last version that worked properly: 
```

**Comment by Brandawg93** [comment] 2020-09-17 23:46
This is a duplicate of #264. Feel free to follow the thread there for updates.

**Closed** 2020-09-17 23:46 UTC
Labels: bug
