### ISSUE TITLE
static image instead of stream. 

### ISSUE THREAD

**Issue by De1F1eD** [Brandawg93/homebridge-nest-cam#30] opened 2020-04-25 13:18 UTC
well i am getting only static image and then on this image starts a counting1,2,3,4,5...etc its seconds and then minutes etc. 
when i open the cam on full screen i get an endless loading in the middle of that static image. 
i ve checked the ffmpeg...changed path... uninstall...reinstall... dont know what i ve done wrong. really i am not an expert but i can follow instructions well and i am confused. 
i m attaching some photos . 

![image](https://user-images.githubusercontent.com/64270667/80281015-dd490c80-8710-11ea-8068-ff998c6aebf2.png)
![image](https://user-images.githubusercontent.com/64270667/80281016-e043fd00-8710-11ea-9d45-d25e5e9cc77d.png)
![Untitled](https://user-images.githubusercontent.com/64270667/80281048-24370200-8711-11ea-8349-aeb64f73442a.png)

**Comment by Brandawg93** [comment] 2020-04-25 13:26
The path to ffmpeg has to end with `ffmpeg` meaning it’s the path to the binary including the binary itself. If you type that path into command prompt and append `-version` it should give you the version of ffmpeg you are using. If not, the path is incorrect.

**Comment by De1F1eD** [comment] 2020-04-25 13:32
yes i changed that and i checked both C:\Users\Unknown\AppData\Roaming\npm\node_modules\homebridge-nest-cam2\node_modules\ffmpeg-for-homebridge\ffmpeg
and
C:\ffmpeg\bin\ffmpeg
and shoes up the -version correcty

which one should i choose and with what  codec??           "ffmpegCodec": "libx264", ?

**Comment by Brandawg93** [comment] 2020-04-25 13:37
You may not need to specify a path to ffmpeg. I bundle the plugin with a static image of ffmpeg in case issues like this arise. What happens if you remove that option completely? Also you can run `ffmpeg -codecs` to see a list of codecs. `libx264` is the most used but may not be on your specific version of ffmpeg.

**Comment by De1F1eD** [comment] 2020-04-25 13:42
configuration: --arch=x86_64 --target-os=mingw32 --host-os=x86_64-w64-mingw32 --disable-ffprobe --enable-ffmpeg --disable-ffplay --disable-bsfs --disable-avdevice --disable-postproc --disable-doc --disable-bzlib --enable-w32threads --enable-gpl --enable-version3 --enable-nonfree --enable-dxva2 --enable-libmfx --enable-nvdec --disable-encoders --enable-encoder=libmp3lame --enable-libmp3lame --enable-encoder=aac --enable-encoder=libx264 --enable-libx264 --enable-encoder=h264_qsv --enable-encoder=h264_amf --enable-encoder=h264_nvenc --pkg-config=pkg-config --prefix=/F/ffmpeg/bulid --disable-static --enable-shared

**Comment by De1F1eD** [comment] 2020-04-25 13:42
D.V.L. h263i                Intel H.263
 D.V.L. h263p                H.263+ / H.263-1998 / H.263 version 2
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv h264_cuvid ) (encoders: libx264 h264_amf h264_nvenc h264_qsv )
 D.VIL. hap                  Vidvox Hap

**Comment by De1F1eD** [comment] 2020-04-25 13:43
i see it there... isnt it? and yes my default option was without the path. but same problem... only still image .. not cam stream

**Comment by Brandawg93** [comment] 2020-04-25 13:47
What does the output say when you run homebridge in debug mode? All ffmpeg errors are output in that mode.

**Comment by De1F1eD** [comment] 2020-04-25 13:48
could you tell me how to do that?

**Comment by Brandawg93** [comment] 2020-04-25 13:49
Sure. If using the config-ui, there is an option in settings to enable debug mode. If using command line you append `-D` after homebridge.

**Comment by De1F1eD** [comment] 2020-04-25 13:55
[4/25/2020, 4:44:09 PM] [Config] Homebridge restart request received
[4/25/2020, 4:44:09 PM] [eWeLink] API reported that [Living Room Spots] is Off
[4/25/2020, 4:44:09 PM] [Config] UI / Bridge settings have not changed; only restarting Homebridge process
[4/25/2020, 4:44:09 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[4/25/2020, 4:44:09 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGTERM
[4/25/2020, 4:44:14 PM] [HB Supervisor] Restarting Homebridge...
[4/25/2020, 4:44:14 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/25/2020, 4:44:14 PM] [HB Supervisor] Started Homebridge with PID: 18888
[4/25/2020, 4:44:14 PM] [HB Supervisor] Sending SIGKILL to Homebridge
[4/25/2020, 4:44:14 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGKILL
[4/25/2020, 4:44:19 PM] [HB Supervisor] Restarting Homebridge...
[4/25/2020, 4:44:19 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[4/25/2020, 4:44:19 PM] [HB Supervisor] Started Homebridge with PID: 19268
[4/25/2020, 4:44:19 PM] Loaded config.json with 0 accessories and 4 platforms.
[4/25/2020, 4:44:19 PM] ---
[4/25/2020, 4:44:20 PM] Loaded plugin: homebridge-config-ui-x
[4/25/2020, 4:44:20 PM] Registering platform 'homebridge-config-ui-x.config'
[4/25/2020, 4:44:20 PM] ---
[4/25/2020, 4:44:20 PM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
[4/25/2020, 4:44:20 PM] Registering platform 'homebridge-eWeLink.eWeLink'
[4/25/2020, 4:44:20 PM] ---
[4/25/2020, 4:44:20 PM] Loaded plugin: homebridge-mqtt-nestthermostat
[4/25/2020, 4:44:20 PM] Registering accessory 'homebridge-mqtt-nestthermostat.mqtt-nestthermostat'
[4/25/2020, 4:44:20 PM] ---
[4/25/2020, 4:44:20 PM] Loaded plugin: homebridge-nest
[4/25/2020, 4:44:20 PM] Registering platform 'homebridge-nest.Nest'
[4/25/2020, 4:44:20 PM] ---
[4/25/2020, 4:44:20 PM] Loaded plugin: homebridge-nest-cam2
[4/25/2020, 4:44:20 PM] Registering platform 'homebridge-nest-cam.Nest-cam'
[4/25/2020, 4:44:20 PM] ---
[4/25/2020, 4:44:20 PM] Loading 4 platforms...
[4/25/2020, 4:44:20 PM] [Config] Initializing config platform...
[4/25/2020, 4:44:20 PM] [Config] Running in Service Mode
[4/25/2020, 4:44:20 PM] [Nest] Initializing Nest platform...
[4/25/2020, 4:44:20 PM] [Nest] Fetching Nest devices.
[4/25/2020, 4:44:20 PM] [Nest-cam] Initializing Nest-cam platform...
[4/25/2020, 4:44:20 PM] [eWeLink] Initializing eWeLink platform...
[4/25/2020, 4:44:20 PM] [eWeLink] Intialising eWeLink
[4/25/2020, 4:44:20 PM] [eWeLink] Found 1 group(s)
[4/25/2020, 4:44:20 PM] Loading 0 accessories...
[4/25/2020, 4:44:20 PM] [eWeLink] Living Room Spots Configure Accessory
[4/25/2020, 4:44:20 PM] [eWeLink] A total of [1] accessories were loaded from the local cache
[4/25/2020, 4:44:20 PM] [eWeLink] Sending login request with user credentials: {"email":"statharas.thanasis@gmail.com","password":"aa250219860a=","version":"6","ts":"1587822260","nonce":"158782226082800","appid":"oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq","imei":"91f96726-8633-11ea-bc55-0242ac130003","os":"iOS","model":"iPhone10,6","romVersion":"11.1.2","appVersion":"3.5.3"}
[4/25/2020, 4:44:20 PM] [eWeLink] Login signature: oAhS11todPiY5dB4HKm45A2zIjWfL04DvKic2NOi1HA=
[4/25/2020, 4:44:22 PM] [eWeLink] Authentication token received [9f8942bab600a22ebed1f2af29efa49323776f50]
[4/25/2020, 4:44:24 PM] [eWeLink] WebSocket host received [eu-pconnect4.coolkit.cc]
[4/25/2020, 4:44:24 PM] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-api.coolkit.cc:8080]
[4/25/2020, 4:44:24 PM] [Nest-cam] Create camera - Front Yard (Αυλή)
[4/25/2020, 4:44:24 PM] Front Yard (Αυλή) is running on port 58936.
[4/25/2020, 4:44:24 PM] Please add [Front Yard (Αυλή)] manually in Home app. Setup Code: 306-97-968
[4/25/2020, 4:44:24 PM] [eWeLink] eWeLink HTTPS API reports that there are a total of [1] devices registered
[4/25/2020, 4:44:24 PM] [eWeLink] Evaluating if devices need to be removed...
[4/25/2020, 4:44:24 PM] [eWeLink] Verifying that all cached devices are still registered with the API. Devices that are no longer registered with the API will be removed.
[4/25/2020, 4:44:24 PM] [eWeLink] [Living Room Spots] Device is registered with API. ID: (bea66f83-4921-494e-9d77-e3f3c49041ac). Nothing to do.
[4/25/2020, 4:44:24 PM] [eWeLink] Evaluating if new devices need to be added...
[4/25/2020, 4:44:24 PM] [eWeLink] Device with ID [1000a49924] is already configured. Ensuring that the configuration is current.
[4/25/2020, 4:44:24 PM] [eWeLink] Device type for 1 is SOCKET
[4/25/2020, 4:44:24 PM] [eWeLink] Single channel device has been set: PSF-BD1-GL uiid: 1
[4/25/2020, 4:44:24 PM] [eWeLink] Updating recorded Characteristic.On for [Living Room Spots] to [false]. No request will be sent to the device.
[4/25/2020, 4:44:24 PM] [eWeLink] API key retrieved from web service is [3b913334-0a4b-4f64-b231-9bf8f0669da6]
[4/25/2020, 4:44:24 PM] [eWeLink] Connecting to the WebSocket API at [wss://eu-pconnect4.coolkit.cc:8080/api/ws]
[4/25/2020, 4:44:26 PM] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"158782226666600","apkVesrion":"1.8","os":"ios","at":"9f8942bab600a22ebed1f2af29efa49323776f50","apikey":"3b913334-0a4b-4f64-b231-9bf8f0669da6","ts":"1587822266","model":"iPhone10,6","romVersion":"11.1.2","sequence":1587822266666}]
[4/25/2020, 4:44:26 PM] [eWeLink] WebSocket messge received:  {"error":0,"apikey":"3b913334-0a4b-4f64-b231-9bf8f0669da6","config":{"hb":1,"hbInterval":145},"sequence":"1587822266666"}
[4/25/2020, 4:44:27 PM] [Nest] initing thermostat "Floor Heating Thermostat": deviceId: 09AA01AC3219030K structureId: 98f386a1-480e-11ea-ad9f-0e46c9c58e3a
[4/25/2020, 4:44:27 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 98f386a1-480e-11ea-ad9f-0e46c9c58e3a structureId: 98f386a1-480e-11ea-ad9f-0e46c9c58e3a
[4/25/2020, 4:44:27 PM] [Nest] Initializing platform accessory 'Floor Heating Thermostat'...
[4/25/2020, 4:44:27 PM] [Nest] Initializing platform accessory 'Home Occupied'...
Setup Payload:
X-HM://0023Z7ISW6PJN
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 306-97-968 │     
    └────────────┘     
                       
[4/25/2020, 4:44:27 PM] Homebridge is running on port 51926.
[4/25/2020, 4:44:29 PM] [eWeLink] Requesting power state for [Living Room Spots]
[4/25/2020, 4:44:30 PM] [eWeLink] API reported that [Living Room Spots] is Off
[4/25/2020, 4:44:33 PM] [eWeLink] Requesting power state for [Living Room Spots]
[4/25/2020, 4:44:33 PM] [eWeLink] API reported that [Living Room Spots] is Off
[4/25/2020, 4:46:19 PM] [eWeLink] Requesting power state for [Living Room Spots]
[4/25/2020, 4:46:19 PM] [eWeLink] API reported that [Living Room Spots] is Off
[4/25/2020, 4:46:24 PM] [Nest-cam] [NexusStreamer] Connected
[4/25/2020, 4:46:24 PM] [Nest-cam] [NexusStreamer] Redirecting...
[4/25/2020, 4:46:24 PM] [Nest-cam] [NexusStreamer] Disconnected
[4/25/2020, 4:46:25 PM] [Nest-cam] [NexusStreamer] Connected
[4/25/2020, 4:46:30 PM] [Nest-cam] [NexusStreamer] Disconnected

**Comment by De1F1eD** [comment] 2020-04-25 13:58
i dont see any errors about ffmpeg
but.. you see this connected and disconnected... happens when i fullscreen the cam from my iphone.. but not real streamming happens... only static image and a loading in the middle

**Comment by De1F1eD** [comment] 2020-04-25 14:03
did u see anything unusual?

**Comment by Brandawg93** [comment] 2020-04-25 14:04
I’ve deleted your last comment because it had a username and password in it. It looks like ffmpeg is never starting. If it did, the output would show your ffmpeg version. I’m not familiar with setting up ffmpeg on Windows personally as I use Linux, but someone in the new discord server may be able to help you there. I’ve seen several people in there who use windows. You can join [here](https://discord.gg/pc2pqmh). Trying posting about this in there as well while I continue to look at it.

**Comment by De1F1eD** [comment] 2020-04-25 14:04
[4/25/2020, 4:54:33 PM] [Nest-cam] [NexusStreamer] Redirecting...
[4/25/2020, 4:54:33 PM] [Nest-cam] [NexusStreamer] Disconnected
[4/25/2020, 4:54:34 PM] [Nest-cam] [NexusStreamer] Connected
[4/25/2020, 4:54:35 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEA"}]
[4/25/2020, 4:54:35 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEA"}]
[4/25/2020, 4:54:35 PM] [Nest-cam] [NexusStreamer] Disconnected
[4/25/2020, 4:55:27 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEB"}]
[4/25/2020, 4:55:27 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEB"}]
[4/25/2020, 4:55:28 PM] [Nest-cam] [NexusStreamer] Connected
[4/25/2020, 4:55:28 PM] [Nest-cam] [NexusStreamer] Redirecting...
[4/25/2020, 4:55:28 PM] [Nest-cam] [NexusStreamer] Disconnected
[4/25/2020, 4:55:29 PM] [Nest-cam] [NexusStreamer] Connected
[4/25/2020, 4:55:59 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEA"}]
[4/25/2020, 4:55:59 PM] [Config] [HapClient] [192.168.0.156:61075 (13:04:2C:95:4E:26)] Got Event: [{"aid":1,"iid":28,"value":"AQEA"}]
[4/25/2020, 4:56:00 PM] [Nest-cam] [NexusStreamer] Disconnected

**Comment by De1F1eD** [comment] 2020-04-25 14:05
yeah so 99% its the ffmpeg that is not starting to encode...thats why i have static image...right?

**Comment by De1F1eD** [comment] 2020-04-25 14:06
and in the debug mode when it works it will show up? can u send me a screenshot of it to be sure what to expect when i fix it?

**Comment by De1F1eD** [comment] 2020-04-25 14:07
i mean the ffmpeg version... how will it look... only one line?

**Comment by Brandawg93** [comment] 2020-04-25 14:08
Correct. When you run homebridge in debug mode, you will see ffmpeg output no matter what. If ffmpeg fails you will only see about 3 lines of output. If it works, you will see hundreds.

**Comment by De1F1eD** [comment] 2020-04-25 14:14
and it has to be the ffmpeg coming with the plugin or i can use the path to the other i downloaded from https://ffmpeg.zeranoe.com/builds/ ?
maybe i messed up i am afraid and i have to uninstall everything about ffmpeg and get it again...

**Comment by Brandawg93** [comment] 2020-04-25 14:16
The ffmpeg with the plugin is recommended, but installing your own can potentially be faster.

**Comment by De1F1eD** [comment] 2020-04-25 14:16
and i dont knowhow to clean everything from ffmpeg

**Comment by De1F1eD** [comment] 2020-04-25 14:22
anyway thanks.. i ll search a little on that matter.

**Comment by Brandawg93** [comment] 2020-04-25 14:28
No problem. I would recommend posting about this in the discord server. Someone may be able to help in there.

**Comment by De1F1eD** [comment] 2020-04-25 14:31
thanks

**Comment by Kanishkaz** [comment] 2020-05-02 07:02
I just installed this plugin and am getting the same behaviour. There appears to be no errors from FFMPEG.
Here's the output from my log:

`[5/2/2020, 7:01:22 AM] [Nest-cam] ffmpeg version 4.2.git-47773f7 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9.2.0 (Alpine 9.2.0)
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-demuxer=rtsp
  libavutil      56. 40.100 / 56. 40.100
  libavcodec     58. 68.102 / 58. 68.102
  libavformat    58. 38.100 / 58. 38.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 75.100 /  7. 75.100
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

[5/2/2020, 7:01:23 AM] [Nest-cam] [NexusStreamer] Connected
[5/2/2020, 7:01:23 AM] [Nest-cam] [NexusStreamer] OK
[5/2/2020, 7:01:23 AM] [Nest-cam] [NexusStreamer] Redirect
[5/2/2020, 7:01:23 AM] [Nest-cam] [NexusStreamer] Redirecting...
[5/2/2020, 7:01:23 AM] [Nest-cam] waiting for socket to connect
[5/2/2020, 7:01:23 AM] [Nest-cam] [NexusStreamer] Disconnected
[5/2/2020, 7:01:24 AM] [Nest-cam] [NexusStreamer] Connected
[5/2/2020, 7:01:24 AM] [Nest-cam] [NexusStreamer] OK
[5/2/2020, 7:01:25 AM] [Nest-cam] [NexusStreamer] Playback Begin
[5/2/2020, 7:01:29 AM] [Nest-cam] Checking for motion on Kitchen`

**Comment by Brandawg93** [comment] 2020-05-02 12:12
I can tell from your logs that FFMPEG is not installed. If it were you would see a lot of FFMPEG debug output between `connecting...` and `disconnected`. It looks like you are correctly running homebridge in debug mode. All FFMPEG output (both standard and error) are logged in debug mode so you should at least see something.

**Comment by Brandawg93** [comment] 2020-05-02 12:13
Actually, I see the FFMPEG output. What OS are you using?

**Comment by Kanishkaz** [comment] 2020-05-04 07:31
> Actually, I see the FFMPEG output. What OS are you using?

I'm running Homebridge on Ubuntu Server 18 as a Docker container.

**Comment by Brandawg93** [comment] 2020-05-11 23:39
The latest version of this plugin may fix this issue. Let me know if so.

**Comment by Kanishkaz** [comment] 2020-05-12 02:56
Unfortunately this is still not working for me. I get the same behaviour as before. I have also confirmed that I have the correct ffmpeg codecs install by running ffmpeg -codecs

log output:
```
[5/12/2020, 12:29:27 AM] [Nest-cam] Updating info for Kitchen (Kitchen Display)
[5/12/2020, 12:29:30 AM] [Nest-cam] Starting video stream (1280x720, 30 fps, 299 kbps, 1378 mtu)...
[5/12/2020, 12:29:30 AM] [Nest-cam] waiting for socket to connect
[5/12/2020, 12:29:30 AM] [Nest-cam] FFMPEG: received first frame
[5/12/2020, 12:29:34 AM] [Nest-cam] [NexusStreamer] Connected
[5/12/2020, 12:29:35 AM] [Nest-cam] [NexusStreamer] OK
[5/12/2020, 12:29:36 AM] [Nest-cam] [NexusStreamer] Redirect
[5/12/2020, 12:29:36 AM] [Nest-cam] [NexusStreamer] Redirecting...
[5/12/2020, 12:29:36 AM] [Nest-cam] waiting for socket to connect
[5/12/2020, 12:29:36 AM] [Nest-cam] [NexusStreamer] Disconnected
[5/12/2020, 12:29:37 AM] [Nest-cam] [NexusStreamer] Connected
[5/12/2020, 12:29:37 AM] [Nest-cam] Checking for motion on Kitchen (Kitchen Display)
[5/12/2020, 12:29:37 AM] [Nest-cam] Updating info for Kitchen (Kitchen Display)
[5/12/2020, 12:29:38 AM] [Nest-cam] [NexusStreamer] OK
[5/12/2020, 12:29:47 AM] [Nest-cam] Checking for motion on Kitchen (Kitchen Display)
[5/12/2020, 12:29:47 AM] [Nest-cam] Updating info for Kitchen (Kitchen Display)
```

codecs 
```
 DEV.L. h261                 
 DEV.L. h263                 
 D.V.L. h263i                
 DEV.L. h263p                
 DEV.LS h264                  (encoders: libx264 libx264rgb )
 D.VIL. hap                  
 DEV.L. hevc                  (encoders: libx265 )
 D.V.L. hnm4video            ```

**Comment by Kampe** [comment] 2020-05-14 19:09
I see the same behavior with my own compiled version of FFmpeg

**Comment by Brandawg93** [comment] 2020-05-14 19:39
Thanks for showing the debug logs. FFMPEG is throwing an error meaning it’s an issue with your custom compiled ffmpeg. FYI, you cannot use the rpi omx video codec with docker. Try using `libx264`.

**Comment by CocoaBob** [comment] 2020-05-24 03:59
Homebridge provides their build of FFMPEG, we can install that one directly to support `homebridge-nest-cam`, here's the command to install it.

```
sudo curl -Lf# https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-raspbian-armv6l.tar.gz | sudo tar xzf - -C / --no-same-owner
```

**Comment by Brandawg93** [comment] 2020-05-25 18:49
I'm closing this issue since it has been quiet. If anyone has a similar issue to the original submitter, feel free to submit another issue.

**Closed by Brandawg93** 2020-05-25 18:49 UTC
