### ISSUE TITLE
Camera Not Responding

### ISSUE THREAD

**Issue by judas2720** [Brandawg93/homebridge-nest-cam#397] opened 2021-01-22 04:51 UTC
**Describe the bug**
Camera not responding when opening from Home app. Snapshot appears correct but camera fails to load stream.

looking at homebridge log this is what I see:

[1/21/2021, 10:40:25 PM] [Nest-cam] [NexusStreamer] Connected
[1/21/2021, 10:40:25 PM] [Nest-cam] [NexusStreamer] Redirecting...
[1/21/2021, 10:40:25 PM] [Nest-cam] [NexusStreamer] Disconnected
[1/21/2021, 10:40:25 PM] [Nest-cam] [NexusStreamer] Connected
(node:40788) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
(node:40788) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 629)
(node:40788) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1/21/2021, 10:40:29 PM] [Nest-cam] VIDEO: VIDEO: Conversion failed!
[1/21/2021, 10:40:29 PM] [Nest-cam] [NexusStreamer] Disconnected. 

**Debug Output**

**To Reproduce**
Open camera stream

1. 

**Expected behavior**
Camera can stream

Please answer these questions before submitting this issue:
```
On what device are you running homebridge: Mac Mini 
On what iOS version are you having issues: 
14.3
What camera types are having issues: 
Nest Hello
Does this issue occur consistently or randomly: 
Consistent that video will not stream anymore. It used to stream just fine. Logs don’t show any other errors for Nest Cam
If applicable, what was the last version that worked properly: I don’t know the specific build but it was probably 3 or so months ago that I noticed it stopped streaming. Just getting around to filing a note now.
```

**Comment by Brandawg93** [comment] 2021-01-22 12:13
This is a duplicate of #279. Feel free to follow along there. Also check out the [FAQ](https://github.com/Brandawg93/homebridge-nest-cam/wiki/FAQ) for potential fixes.

**Closed by Brandawg93** 2021-01-22 12:13 UTC
Labels: bug
