### ISSUE TITLE
Nest Cam No Response

### ISSUE THREAD

**Issue by jayyzhao** [Brandawg93/homebridge-nest-cam#108] opened 2020-06-26 14:44 UTC
Nest Cam set up and shows up via home kit, however when viewing the camera, it shows that there is no response.  Running the latest v3.3.0

From logs I can see the following:

[6/26/2020, 7:37:15 AM] [Nest-cam] [NexusStreamer] Connected
[6/26/2020, 7:37:16 AM] [Nest-cam] [NexusStreamer] Redirecting...
[6/26/2020, 7:37:16 AM] [Nest-cam] [NexusStreamer] Disconnected
[6/26/2020, 7:37:16 AM] [Nest-cam] [NexusStreamer] Redirecting...
[6/26/2020, 7:37:16 AM] [Nest-cam] [NexusStreamer] Disconnected
[6/26/2020, 7:37:16 AM] [Nest-cam] [NexusStreamer] Connected

On homekit, it still shows that no response / this camera is not responding. 

This is happening to all my cameras in nest.

**Comment by Brandawg93** [comment] 2020-06-26 14:46
Did it work in v3.2?

**Comment by jayyzhao** [comment] 2020-06-26 14:53
Just tested with 3.2.2. Same  thing occurs. Logs show the same. 

[6/26/2020, 7:53:07 AM] [Nest-cam] [NexusStreamer] Disconnected
[6/26/2020, 7:53:08 AM] [Nest-cam] [NexusStreamer] Connected
[6/26/2020, 7:53:08 AM] [Nest-cam] [NexusStreamer] Redirecting...
[6/26/2020, 7:53:09 AM] [Nest-cam] [NexusStreamer] Disconnected
[6/26/2020, 7:53:09 AM] [Nest-cam] [NexusStreamer] Connected
[6/26/2020, 7:53:09 AM] [Nest-cam] [NexusStreamer] Disconnected
[6/26/2020, 7:53:09 AM] [Nest-cam] [NexusStreamer] Connected

**Comment by Brandawg93** [comment] 2020-06-26 14:56
Those logs look completely normal. So it looks like your FFmpeg processes are running correctly and sending data. Usually, this means the issue is between homebridge and your device. What OS are you running?

**Comment by jayyzhao** [comment] 2020-06-26 14:59
Running home bridge via unraid docker. You think its related to the OS/Env? 

Let me install it on Mac and try.

**Comment by Brandawg93** [comment] 2020-06-26 15:01
I'm starting to think so. Every user on unraid that I've talked to cannot get cameras to work. Make sure you are running in host mode on docker.

**Comment by jayyzhao** [comment] 2020-06-26 23:37
Can Confirm - that its related to the unraid / docker version. I've installed it on a Mac and is working flawlessly.

**Comment by johnsanc314** [comment] 2020-06-27 21:27
Confirmed I have the exact same issue with the Unraid docker in host network mode - any idea how to get this working?

**Comment by MxD-js** [comment] 2020-09-16 18:03
for anyone having issues w/ Docker and not responding/live stream not working. Add this to your startup.sh script located in your homebridge config directory, and restart. This will install ffmpeg. 

apk add --no-cache ffmpeg ffmpeg-libs

**Comment by ckaylin** [comment] 2020-12-27 16:51
Just updated today and most of the time video streaming fails with a JavaScript error:

[27/12/2020, 08:48:54] [Nest-cam] [NexusStreamer] Connected
[27/12/2020, 08:48:54] [Nest-cam] [NexusStreamer] Redirecting...
[27/12/2020, 08:48:54] [Nest-cam] [NexusStreamer] Disconnected
[27/12/2020, 08:48:54] [Nest-cam] [NexusStreamer] Connected
[27/12/2020, 08:49:24] [Nest-cam] [NexusStreamer] Disconnected
(node:15421) UnhandledPromiseRejectionWarning: Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
(node:15421) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

Maybe one out of five times the video will come up. I think there's an underlying timeout somewhere but it's not clear to me where to look.

**Comment by Brandawg93** [comment] 2020-12-27 16:56
@ckaylin What are you running homebridge on? It sounds like the device isn't fast enough to process the video.

**Comment by ckaylin** [comment] 2020-12-27 16:58
Hi @Brandawg93 it's a new-ish Pi4. Homebridge shows the CPU at < 5% load, and there's tons of storage on the flash card

**Comment by ckaylin** [comment] 2020-12-27 17:00
One other thing I can say is that even with the Nest's native app or their web page, the cameras can take a while to start streaming. Perhaps there's a timeout set a bit too low in the NexusStreamer code?

**Comment by Brandawg93** [comment] 2020-12-27 20:36
@ckaylin Unless you're running homebridge on Docker, your issue doesn't seem to be related to the current thread. If you're still having issues with this feel free to create new issue. I'm going to close this one again.

**Closed by Brandawg93** 2020-12-27 20:36 UTC
Labels: bug
