### ISSUE TITLE
Support Google App-Specific Password

### ISSUE THREAD

**Issue by humanthrope** [Brandawg93/homebridge-nest-cam#175] opened 2020-08-11 06:30 UTC
**Is your feature request related to a problem? Please describe.**
With 2FA enabled on my Google account, I find it problematic to use the built-in login.js (and cannot get it to work at all frequently) and it is cumbersome to fetch the tokens manually with an incognito browser window. Plus from what I've read it appears this authentication method expires after some period of time, which means that I'll find that the plugin spontaneously stops working one day and, annoyingly, have to start the process over.

**Describe the solution you'd like**
Google accounts support app passwords. It seems to me that this might be an easy way to avoid the token problem above.

https://support.google.com/accounts/answer/185833?hl=en

**Describe alternatives you've considered**
homebridge-ring has ring-auth-cli and and can automatically renew the tokens. Perhaps this might work, but app passwords seems easier IMHO.

https://github.com/dgreif/ring/wiki/Refresh-Tokens

**Comment by Brandawg93** [comment] 2020-08-11 12:06
Google and Ring use two fundamentally differenct login methods. Ring is using OAuth which is specifcally designed for developers to take advantage of and create apps like the ring-auth-cli. Google, on the other hand, has designed their login process to be as difficult as possible to use specifically for developers to not use it. 

With that said, app-specific passwords will not work for nest-cam because it is using Google's web login which doesn't support it.

As far as your 2FA, have you tried using the `-h` flag to force the login process to use a headful browser? It may make it easier for you.

**Comment by humanthrope** [comment] 2020-08-11 14:38
Shame about the web logins :(

I'll give -h another try. I had tried it before, but didn't realize it started up a GUI browser. I usually use the homebridge machine headless, even though it has a monitor attached and didn't see that Chromium had launched. It looked no different than running without -h, although it just hanged forever.

**Comment by Brandawg93** [comment] 2020-08-11 14:47
Ya. You would need to run it with a monitor. I actually run the login process on my Macbook and copy the results over to my Pi 4. You don't have to run the login process on the same machine as homebridge.

This Fall, Google will be releasing their [Device Access Program](https://developers.google.com/nest/device-access) which will make this much easier. The current login process is just a temporary fix until then.

**Comment by Brandawg93** [comment] 2020-08-12 11:09
I am going to close this for now since there isn't much I can do until Google releases the DAP. A better login process is definitely on the road map, though.

**Closed by Brandawg93** 2020-08-12 11:09 UTC
Labels: enhancement
