### ISSUE TITLE
Alpine Linux (3.12.0) homebridge-nest-cam login not working

### ISSUE THREAD

**Issue by thecem** [Brandawg93/homebridge-nest-cam#142] opened 2020-07-23 17:45 UTC
**Before Submitting an Issue**

https://github.com/Brandawg93/homebridge-nest-cam/wiki/Troubleshooting

Make sure you have the latest LTS from https://nodejs.org
and the latest packages: `npm upgrade -g homebridge homebridge-nest-cam`

Also include debug log output from startup through seeing the issue:
`homebridge -D`

**Describe the bug**

Above is al the latest:

OS | Alpine Linux  (3.12.0)
hassio (Docker with latest OZNU image)
Node v12.18.3
NPM v6.14.6
root

```
/homebridge/node_modules/homebridge-nest-cam # node dist/login.js
Unable to retrieve credentials.
Error: Failed to launch the browser process! spawn /homebridge/node_modules/homebridge-nest-cam/node_modules/puppeteer/.local-chromium/linux-756035/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/homebridge/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at ChildProcess.<anonymous> (/homebridge/node_modules/homebridge-nest-cam/node_modules/puppeteer/lib/launcher/BrowserRunner.js:151:82)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
/homebridge/node_modules/homebridge-nest-cam # 

```
**To Reproduce**

1.  Install Docker Homebridge
2.  Install homebridge-nest-cam
3. run in Homebridge UI-X Terminal:  node dist/login.js

**Expected behavior**

login to google and giving the auth

Please answer these questions before submitting this issue:
```
On what OS are you running homebridge: Alpine Linux  (3.12.0) // oznu/homebridge:latest Docker image with Node v12.18.3 and NPM v6.14.6
What camera types are having issues: Hello
Does this issue occur consistently or randomly: consistently 
If applicable, what was the last version that worked properly: ???
```

**Comment by Brandawg93** [comment] 2020-07-23 18:19
This is a known issue. For now, just use the [manual authentication](https://github.com/Brandawg93/homebridge-nest-cam/wiki/Manual-Authentication) method. When Google releases the Device Access Program, I'll be able to fix this.

**Comment by Brandawg93** [comment] 2020-07-28 12:45
I'm going to close this since it is a duplicate of #143, but here is the latest update from there:

I've added a `-p` flag to the login function that will allow you to specify the executable path. It will be available in the next release. If you would like to try it, you can install it via `npm -g i homebridge-nest-cam@test --unsafe-perm`

**Closed by Brandawg93** 2020-07-28 12:45 UTC
Labels: bug
